WeaponUpgradeSpecifier
Weapon WeaponUpgradeSpecifier._weapon
Referenced by WeaponUpgradeSpecifier, UpgradeByPercentage, UpgradeByAmount, Build.
string WeaponUpgradeSpecifier._name
Referenced by Named, Build.
WeaponUpgradeSpecifier.WeaponUpgradeSpecifier(Weapon weapon)
References _weapon.
Referenced by FromWeapon.
static WeaponUpgradeSpecifier WeaponUpgradeSpecifier.FromWeapon(Weapon baseWeapon)
References WeaponUpgradeSpecifier.
Referenced by SkyNet.CreateRobot.
WeaponUpgradeSpecifier WeaponUpgradeSpecifier.UpgradeByPercentage(int percentBonus)
References _weapon.
Referenced by SkyNet.CreateRobot.
WeaponUpgradeSpecifier WeaponUpgradeSpecifier.UpgradeByAmount(int bonus)
References _weapon.
Referenced by SkyNet.CreateRobot.
WeaponUpgradeSpecifier WeaponUpgradeSpecifier.Named(string name)
References _name.
Referenced by SkyNet.CreateRobot.
Weapon WeaponUpgradeSpecifier.Build()
References _name, _weapon, Weapon.Name.
Referenced by SkyNet.CreateRobot.