Robowars::WeaponUpgradeSpecifier
Weapon Robowars.WeaponUpgradeSpecifier._weapon
Referenced by Robowars.WeaponUpgradeSpecifier.WeaponUpgradeSpecifier, Robowars.WeaponUpgradeSpecifier.UpgradeByPercentage, Robowars.WeaponUpgradeSpecifier.UpgradeByAmount, Robowars.WeaponUpgradeSpecifier.Build.
string Robowars.WeaponUpgradeSpecifier._name
Referenced by Robowars.WeaponUpgradeSpecifier.Named, Robowars.WeaponUpgradeSpecifier.Build.
Robowars.WeaponUpgradeSpecifier.WeaponUpgradeSpecifier(Weapon weapon)
References Robowars.WeaponUpgradeSpecifier._weapon.
Referenced by Robowars.WeaponUpgradeSpecifier.FromWeapon.
static WeaponUpgradeSpecifier Robowars.WeaponUpgradeSpecifier.FromWeapon(Weapon baseWeapon)
References Robowars.WeaponUpgradeSpecifier.WeaponUpgradeSpecifier.
Referenced by Robowars.SkyNet.CreateWeapons.
WeaponUpgradeSpecifier Robowars.WeaponUpgradeSpecifier.UpgradeByPercentage(int percentBonus)
References Robowars.WeaponUpgradeSpecifier._weapon.
Referenced by Robowars.SkyNet.CreateWeapons.
WeaponUpgradeSpecifier Robowars.WeaponUpgradeSpecifier.UpgradeByAmount(int bonus)
References Robowars.WeaponUpgradeSpecifier._weapon.
Referenced by Robowars.SkyNet.CreateWeapons.
WeaponUpgradeSpecifier Robowars.WeaponUpgradeSpecifier.Named(string name)
References Robowars.WeaponUpgradeSpecifier._name.
Referenced by Robowars.SkyNet.CreateWeapons.
Weapon Robowars.WeaponUpgradeSpecifier.Build()
References Robowars.WeaponUpgradeSpecifier._name, Robowars.WeaponUpgradeSpecifier._weapon, Robowars.Weapon.Name.
Referenced by Robowars.SkyNet.CreateWeapons.