Robowars::Contest
Robot Robowars.Contest.Contestant1
Referenced by Robowars.Contest.ShowStatus, Robowars.Contest.ShowMenu, Robowars.Contest.Fight.
Robot Robowars.Contest.Contestant2
Referenced by Robowars.Contest.ShowStatus, Robowars.Contest.ShowMenu, Robowars.Contest.Fight.
RobotAssembler Robowars.Contest.TerminatorFacility
Referenced by Robowars.Contest.ShowMenu.
RobotAssembler Robowars.Contest.MiningFacility
Referenced by Robowars.Contest.ShowMenu.
MiningRobotMaker Robowars.Contest._miningRobotMaker
void Robowars.Contest.ShowStatus()
Shows the status of the two contestants
References Robowars.Contest.Contestant1, Robowars.Contest.Contestant2, Robowars.Robot.Report.
Referenced by Robowars.Contest.ShowMenu.
void Robowars.Contest.ShowMenu()
Shows a menu where the user can select a command to organize and initiate a fight
References Robowars.RobotAssembler.AssembleRobot, Robowars.Contest.Contestant1, Robowars.Contest.Contestant2, Robowars.Contest.Fight, Robowars.Contest.MiningFacility, Robowars.Contest.ShowStatus, Robowars.Contest.TerminatorFacility.
Referenced by Robowars.Program.Main.
void Robowars.Contest.Fight()
References Robowars.Robot.ActivateIfPossible, Robowars.Contest.Contestant1, Robowars.Contest.Contestant2.
Referenced by Robowars.Contest.ShowMenu.