Robowars::Weapons::WeaponUpgradeSpecifier
Weapon Robowars.Weapons.WeaponUpgradeSpecifier._weapon
string Robowars.Weapons.WeaponUpgradeSpecifier._name
Robowars.Weapons.WeaponUpgradeSpecifier.WeaponUpgradeSpecifier(Weapon weapon)
static WeaponUpgradeSpecifier Robowars.Weapons.WeaponUpgradeSpecifier.FromWeapon(Weapon baseWeapon)
Referenced by Robowars.SkyNet.CreateRobot.
WeaponUpgradeSpecifier Robowars.Weapons.WeaponUpgradeSpecifier.UpgradeByPercentage(int percentBonus)
Referenced by Robowars.SkyNet.CreateRobot.
WeaponUpgradeSpecifier Robowars.Weapons.WeaponUpgradeSpecifier.UpgradeByAmount(int bonus)
Referenced by Robowars.SkyNet.CreateRobot.
WeaponUpgradeSpecifier Robowars.Weapons.WeaponUpgradeSpecifier.Named(string name)
Referenced by Robowars.SkyNet.CreateRobot.
Weapon Robowars.Weapons.WeaponUpgradeSpecifier.Build()
References Robowars.Weapons.Weapon.Name.
Referenced by Robowars.SkyNet.CreateRobot.