Robowars::RobotAssembler
Robot Robowars.RobotAssembler.AssembleRobot()
Creates a new robot.
References Robowars.RobotAssembler.CreateWeapons, Robowars.RobotAssembler.Name.
Referenced by Robowars.Contest.ShowMenu.
abstract string Robowars.RobotAssembler.Name()
Returns the name for a newly created robot.
Referenced by Robowars.RobotAssembler.AssembleRobot.
abstract List<Weapon> Robowars.RobotAssembler.CreateWeapons()
Creates weaponry for the robot.
Referenced by Robowars.RobotAssembler.AssembleRobot.