Robowars::Robot
RobotSituation Robowars.Robot.Situation
Referenced by Robowars.Robot.Robot, Robowars.Robot.TakeDamage, Robowars.Robot.Attack, Robowars.Robot.ActivateIfPossible, Robowars.Robot.Active.Deactivate, Robowars.Robot.Active.Destroy, Robowars.Robot.Active.Attack, Robowars.Robot.Attacking.Ready, Robowars.Robot.Standby.Ready, Robowars.Robot.Standby.Destroy.
string Robowars.Robot.Name
Referenced by Robowars.Robot.Robot.
int Robowars.Robot.PowerLevel
Is both the health and ability to attack for a robot.
Referenced by Robowars.Robot.Robot, Robowars.Robot.Attack, Robowars.Robot.RobotSituation.TakeDamage.
IEnumerable<Weapon> Robowars.Robot.Weapons
bool Robowars.Robot.IsDestroyed
bool Robowars.Robot.IsActive
bool Robowars.Robot.IsStandby
bool Robowars.Robot.IsMoving
List<Weapon> Robowars.Robot._weapons
Referenced by Robowars.Robot.Robot, Robowars.Robot.Attack.
Robowars.Robot.Robot(string name, IEnumerable< Weapon > weapons)
References Robowars.Robot._weapons, Robowars.Robot.Name, Robowars.Robot.PowerLevel, Robowars.Robot.Situation.
void Robowars.Robot.TakeDamage(int damage, string description)
References Robowars.Robot.Situation, Robowars.Robot.RobotSituation.TakeDamage.
Referenced by Robowars.Robot.Attack.
void Robowars.Robot.Report()
Referenced by Robowars.Contest.ShowStatus.
void Robowars.Robot.Attack(Robot other)
Robot attacks the other robot with a random weapon, if the situation allows.
References Robowars.Robot._weapons, Robowars.Robot.RobotSituation.Attack, Robowars.Robot.RobotSituation.Deactivate, Robowars.Robot.PowerLevel, Robowars.Robot.Situation, Robowars.Robot.TakeDamage.
void Robowars.Robot.ActivateIfPossible()
References Robowars.Robot.RobotSituation.Ready, Robowars.Robot.Situation.
Referenced by Robowars.Contest.Fight.