Robowars::Robot::RobotSituation
Robot Robowars.Robot.RobotSituation.Context
Referenced by Robowars.Robot.RobotSituation.RobotSituation, Robowars.Robot.RobotSituation.TakeDamage, Robowars.Robot.Active.Deactivate, Robowars.Robot.Active.Destroy, Robowars.Robot.Active.Attack, Robowars.Robot.Attacking.Ready, Robowars.Robot.Standby.Ready, Robowars.Robot.Standby.Destroy.
string Robowars.Robot.RobotSituation.Feedback
Referenced by Robowars.Robot.RobotSituation.RobotSituation, Robowars.Robot.Active.Ready, Robowars.Robot.Attacking.Attack, Robowars.Robot.Standby.Deactivate, Robowars.Robot.Standby.Attack, Robowars.Robot.Destroyed.Ready, Robowars.Robot.Destroyed.Deactivate, Robowars.Robot.Destroyed.Attack, Robowars.Robot.Destroyed.Destroy.
virtual string Robowars.Robot.RobotSituation.Description
Robowars.Robot.RobotSituation.RobotSituation()
Robowars.Robot.RobotSituation.RobotSituation(Robot context, string feedback="")
References Robowars.Robot.RobotSituation.Context, Robowars.Robot.RobotSituation.Feedback.
abstract bool Robowars.Robot.RobotSituation.Ready()
Referenced by Robowars.Robot.ActivateIfPossible.
abstract bool Robowars.Robot.RobotSituation.Attack()
Referenced by Robowars.Robot.Attack.
abstract bool Robowars.Robot.RobotSituation.Deactivate()
Referenced by Robowars.Robot.Attack.
void Robowars.Robot.RobotSituation.TakeDamage(int damage)
References Robowars.Robot.RobotSituation.Context, Robowars.Robot.RobotSituation.Destroy, Robowars.Robot.PowerLevel.
Referenced by Robowars.Robot.TakeDamage.
abstract bool Robowars.Robot.RobotSituation.Destroy(string reason)
Referenced by Robowars.Robot.RobotSituation.TakeDamage.