Robowars::Robots::RobotSituation
Robot Robowars.Robots.RobotSituation.Context
Returns the Robot to which this RobotSituation applies.
Referenced by Robowars.Robots.Active.Deactivate, Robowars.Robots.Active.Destroy, Robowars.Robots.Active.Attack, Robowars.Robots.Attacking.Ready, Robowars.Robots.RobotSituation.RobotSituation, Robowars.Robots.RobotSituation.TakeDamage, Robowars.Robots.Standby.Ready, Robowars.Robots.Standby.Destroy.
string Robowars.Robots.RobotSituation.Feedback
A text description of what happened.
Referenced by Robowars.Robots.Active.Ready, Robowars.Robots.Attacking.Attack, Robowars.Robots.Destroyed.Ready, Robowars.Robots.Destroyed.Deactivate, Robowars.Robots.Destroyed.Attack, Robowars.Robots.Destroyed.Destroy, Robowars.Robots.RobotSituation.RobotSituation, Robowars.Robots.Standby.Deactivate, Robowars.Robots.Standby.Attack.
virtual string Robowars.Robots.RobotSituation.Description
Returns the description for the RobotSituation, typically the name of the situation.
Robowars.Robots.RobotSituation.RobotSituation()
Robowars.Robots.RobotSituation.RobotSituation(Robot context, string feedback="")
References Robowars.Robots.RobotSituation.Context, Robowars.Robots.RobotSituation.Feedback.
abstract bool Robowars.Robots.RobotSituation.Ready()
Attempts a transition to the Active Situation
True when succesful, false when the Robot's RobotSituation was not changed.
Referenced by Robowars.Robots.Robot.ActivateIfPossible.
abstract bool Robowars.Robots.RobotSituation.Attack()
Attempts a transition to the Attacking Situation
True when succesful, false when the Robot's RobotSituation was not changed.
Referenced by Robowars.Robots.Robot.Attack.
abstract bool Robowars.Robots.RobotSituation.Deactivate()
Attempts a transition to the Standby Situation
True when succesful, false when the Robot's RobotSituation was not changed.
Referenced by Robowars.Robots.Robot.Attack.
void Robowars.Robots.RobotSituation.TakeDamage(int damage)
Handles the logic for a Robot taking damage, and transitions the Situation to Destroyed when appropriate.
damage The amount of damage taken
References Robowars.Robots.RobotSituation.Context, Robowars.Robots.RobotSituation.Destroy, Robowars.Robots.Robot.PowerLevel.
Referenced by Robowars.Robots.Robot.TakeDamage.
abstract bool Robowars.Robots.RobotSituation.Destroy(string reason)
Attempts a transition to the Destroyed Situation
True when succesful, false when the Robot's RobotSituation was not changed.
Referenced by Robowars.Robots.RobotSituation.TakeDamage.